### ISSUE TITLE
Attempt to convert args to binaries

### ISSUE THREAD

**Issue by mobileoverlord** [fhunleth/muontrap#2]
When passing an integer through the `MuonTrap.Daemon` args the process fails to start and results in an argument error. The example I have is passing a port number. Converting this to a string and passing it fixes the issue. I am only opening this issue as a placeholder to discuss if we should attempt to convert the args before using them.

**Comment by fhunleth** [comment]
Another option would be to validate parameters and give good error messages. I can't tell you how much time I've wasted staring at `Port.open/2` arguments for either fixing Dialyzer errors or exceptions like the one that you hit.

**Comment by axelson** [comment]
+1 to validating that valid binaries are coming in. I wouldn't prefer an implicit conversion to string because the terms that you pass in may have some special `String.Chars` implementation that the developer is not expecting.

**Comment by fhunleth** [comment]
This will be fixed in the upcoming `v0.5.0` release. 

`MuonTrap.Daemon` validates arguments and raises now. It also validates the other options before they get caught with the less-than-helpful argument error from `Port.open`. This was fixed when refactoring the option parsing code for `MuonTrap.Daemon` and `MuonTrap.cmd/3` to one place.
