### ISSUE TITLE
Fails to compile when there's a space somewhere in the absolute path

### ISSUE THREAD

**Issue by LostKobrakai** [fhunleth/muontrap#21]
```
Fatal error: can't create it/Projekte/rentory/rentory_hub/_build/nerves_system_docker_rpi4_dev/lib/muontrap/obj/muontrap.o: No such file or directory
make[1]: *** [it/Projekte/rentory/rentory_hub/_build/nerves_system_docker_rpi4_dev/lib/muontrap/obj/muontrap.o] Error 2
make: *** [all] Error 2
```

The folder at the start was `/made it/…`

**Comment by fhunleth** [comment]
I did some investigation, and this is an issue with `make`. The page at https://www.cmcrossroads.com/article/gnu-make-meets-file-names-spaces-them has some workarounds, but none of them are great (IMHO). Plus the next `Makefile` in your project will probably fail when this one is fixed. 

I'm not sure how any Elixir project `Makefile` works with spaces in the path unless it either builds in the source directory (so no absolute paths needed) or uses `realpath` to convert `MIX_APP_PATH` to a relative path that doesn't have spaces. Building in the source directory is a non-starter with Nerves. Using `realpath` and passing around relative paths might not work on all systems since not everyone has `realpath`. Using relative paths seems tedious. 

I'm closing this since I don't see it being fixed. If you have a suggestion, please send a PR.

**Comment by LostKobrakai** [comment]
I'm fine with the resolution. I'm just wondering if mountrap might be able to check for that and raise a more descriptive error message / log a warning? I'm not sure people will do the link of having a truncated path printed with their space in path as quickly as I seem to have.

**Comment by LostKobrakai** [comment]
To add a bit more context, why I'm worried about that: I've published [minio_server](https://hex.pm/packages/minio_server) a few days ago, which uses muontrap being not really nerves related, and it might be tricky if one isn't explicitly aware of muontrap in the first place.

**Comment by fhunleth** [comment]
Could you make a PR or send a PR to `elixir_make`? IMHO, adding the check to `elixir_make` would be better since checking if the `MIX_APP_PATH` (or any of the paths that Elixir passes to make) have a space in them seems easy there, and this affects all projects using `make`.
