### ISSUE TITLE
Establishing/Supervising Communications With a Long-Running, Data Streaming Python Process

### ISSUE THREAD

**Issue by Maxximiliann** [fhunleth/muontrap#29]
Ubuntu 20.04.1 LTS
Erlang/OTP 23 [erts-11.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.10.3 (compiled with Erlang/OTP 22)

Our Elixir project requires initiating and then supervising communications with a long-running, data streaming Python process. Data will be pushed to its Elixir counterpart once every second.

Is your library ideally suited for this? If so, where can we find recipes for such a use case?

**Comment by fhunleth** [comment]
If you want to use stdin/stdout for your communications, then it's not suitable since it doesn't expose stdio for application use. There are quite a few alternatives out there that support this use case, like the Rambo library. 

If you're using a Unix domain socket or any kind of TCP connection for communication, then that will work fine. That's a common setup as well. I.e., run a daemon or other long running process from MuonTrap and then connect out-of-band via a socket for interaction.

**Comment by Maxximiliann** [comment]
Thanks so much for your prompt reply. What if the Python and Elixir processes were on the same machine? How would your library be used to manage the Python stream directly to its Elixir counterpart?

**Comment by fhunleth** [comment]
Sorry, I don't know much about interacting with Python. MuonTrap wouldn't be involved at all with the communication. MuonTrap is just responsible for managing the lifecycle of the program - like restarting it if it crashes, cleaning up, or optionally restricting resources with cgroups.
